# Generated by Django 3.0.7 on 2020-06-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200624_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='slug',
            new_name='tutorial_slug',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
