# Generated by Django 3.0.7 on 2020-06-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200624_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='series',
            new_name='tseries',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='series',
            new_name='cseries',
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialCategory', verbose_name='Category'),
        ),
    ]
