# Generated by Django 3.0.7 on 2020-06-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200624_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tseries',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='cseries',
            new_name='series',
        ),
    ]
