# Generated by Django 3.0.7 on 2020-06-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200624_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='content',
            new_name='tutorial_content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='published',
            new_name='tutorial_published',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='series',
            new_name='tutorial_series',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='tutorial_title',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='category',
            new_name='category_summary',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='summary',
            new_name='tutorial_category',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='series',
            new_name='series_summary',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='category',
            new_name='tutorial_category',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='summary',
            new_name='tutorial_series',
        ),
    ]
